documentation:
    - https://docs.x.ai
    - https://docs.x.ai/developers/models#models-and-pricing
    - https://docs.x.ai/developers/models
    - https://docs.x.ai/developers/model-capabilities/text/reasoning
messages:
    options:
        - system
        - user
        - assistant
params:
    - defaultValue: 256
      key: max_tokens
      maxValue: 32768
      minValue: 1
    - defaultValue: 0.7
      key: temperature
      maxValue: 2
      minValue: 0
    - defaultValue: 1
      key: top_p
      maxValue: 1
      minValue: 0
    - defaultValue: 1
      key: "n"
      maxValue: 10
      minValue: 1
    - defaultValue: null
      key: stop
      type: array-of-strings
    - defaultValue: true
      key: stream
      type: boolean
    - defaultValue: low
      key: reasoning_effort
      supportedValues:
          - none
          - low
          - medium
          - high
      type: string
