---
extends: default

rules:
  key-ordering: enable   
  indentation:
    spaces: 4
    indent-sequences: true
  line-length:
    max: 256
  truthy:
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
