documentation:
    - https://docs.aws.amazon.com/bedrock/
    - https://aws.amazon.com/bedrock/pricing/
    - https://docs.aws.amazon.com/bedrock/latest/userguide/model-cards.html
    - https://docs.aws.amazon.com/bedrock/latest/userguide/structured-output.html#structured-output-supported-apis
tool_pricing:
    web_search:
        per_thousand_requests: 12
