params:
  - key: max_tokens
    defaultValue: 256
    minValue: 1
    maxValue: 32768
  - key: temperature
    defaultValue: 0.7
    minValue: 0
    maxValue: 2
  - key: top_p
    defaultValue: 1
    minValue: 0
    maxValue: 1
  - key: seed
    defaultValue: null
    minValue: 0
    maxValue: 1
  - key: stop
    defaultValue: null
    type: array-of-strings
    skipValues:
      - null
      - []
  - key: safe_prompt
    defaultValue: true
    type: boolean
  - key: stream
    defaultValue: true
    type: boolean
messages:
  options:
    - system
    - user
    - assistant
type:
  primary: chat
  supported: []
