documentation:
    - https://cloud.google.com/vertex-ai/generative-ai/pricing
    - https://console.cloud.google.com/vertex-ai/publishers/google/model-garden
    - https://docs.cloud.google.com/vertex-ai/generative-ai/docs/models
    - https://docs.cloud.google.com/vertex-ai/generative-ai/docs/deprecations
messages:
    options:
        - system
        - user
        - assistant
params:
    - defaultValue: 256
      key: max_tokens
      maxValue: 32768
      minValue: 1
    - defaultValue: 0.7
      key: temperature
      maxValue: 2
      minValue: 0
    - defaultValue: 1
      key: top_p
      maxValue: 1
      minValue: 0
    - defaultValue: 1
      key: "n"
      maxValue: 10
      minValue: 1
    - defaultValue: null
      key: stop
      type: array-of-strings
    - defaultValue: true
      key: stream
      type: boolean
    - defaultValue: null
      key: tool_choice
