params:
  - key: max_tokens
    defaultValue: 256
    minValue: 1
    maxValue: 32768
  - key: temperature
    defaultValue: 0.7
    minValue: 0
    maxValue: 2
  - key: top_p
    defaultValue: 1
    minValue: 0
    maxValue: 1
  - key: 'n'
    defaultValue: 1
    minValue: 1
    maxValue: 10
  - key: stop
    defaultValue: null
    type: array-of-strings
    skipValues:
      - null
      - []
  - key: stream
    defaultValue: true
    type: boolean
  - key: tool_choice
    type: non-view-manage-data
    defaultValue: null
    options:
      - value: none
        name: None
      - value: auto
        name: Auto
      - value: required
        name: Required
      - value: custom
        name: Custom
        schema:
          type: json
    skipValues:
      - null
      - []
    rule:
      default:
        condition: tools
        then: auto
        else: null
messages:
  options:
    - system
    - user
    - assistant
type:
  primary: chat
  supported:
    - mime_type
