/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description AWS region identifiers
         * @enum {string}
         */
        AWSRegion: "af-south-1" | "ap-east-1" | "ap-east-2" | "ap-northeast-1" | "ap-northeast-2" | "ap-northeast-3" | "ap-south-1" | "ap-south-2" | "ap-southeast-1" | "ap-southeast-2" | "ap-southeast-3" | "ap-southeast-4" | "ap-southeast-5" | "ap-southeast-6" | "ap-southeast-7" | "ca-central-1" | "ca-west-1" | "cn-north-1" | "cn-northwest-1" | "eu-central-1" | "eu-central-2" | "eu-north-1" | "eu-south-1" | "eu-south-2" | "eu-west-1" | "eu-west-2" | "eu-west-3" | "il-central-1" | "me-central-1" | "me-south-1" | "mx-central-1" | "sa-east-1" | "us-east-1" | "us-east-2" | "us-gov-east-1" | "us-gov-west-1" | "us-west-1" | "us-west-2";
        /** @enum {string} */
        AzureRegion: "datazone_eu" | "datazone_us" | "global";
        /** @description One anthropic-beta column: clientToken -> providerToken, or null to drop */
        BetaColumn: {
            [key: string]: string | null;
        };
        Cost: {
            cache_creation_input_audio_token_cost?: number;
            cache_creation_input_token_cost?: number;
            cache_creation_input_token_cost_per_hour?: number;
            cache_read_input_audio_token_cost?: number;
            cache_read_input_token_cost?: number;
            input_cost_per_annotated_page?: number;
            input_cost_per_audio_token?: number;
            input_cost_per_character?: number;
            input_cost_per_image?: number;
            input_cost_per_image_token?: number;
            input_cost_per_page?: number;
            input_cost_per_query?: number;
            input_cost_per_request?: number;
            input_cost_per_second?: number;
            input_cost_per_token?: number;
            input_cost_per_token_batches?: number;
            input_cost_per_video_token?: number;
            output_cost_per_audio_token?: number;
            output_cost_per_image?: number;
            output_cost_per_image_token?: number;
            output_cost_per_second?: number;
            output_cost_per_token?: number;
            output_cost_per_token_batches?: number;
            output_cost_per_video_token?: number;
            tiered_pricing?: components["schemas"]["TieredPricing"];
        };
        /** @description Pricing entry; "*" applies to all regions */
        CostWithRegion: {
            priority_pricing?: components["schemas"]["Cost"];
            /** @enum {string} */
            region?: "*" | "af-south-1" | "ap-east-1" | "ap-east-2" | "ap-northeast-1" | "ap-northeast-2" | "ap-northeast-3" | "ap-south-1" | "ap-south-2" | "ap-southeast-1" | "ap-southeast-2" | "ap-southeast-3" | "ap-southeast-4" | "ap-southeast-5" | "ap-southeast-6" | "ap-southeast-7" | "ca-central-1" | "ca-west-1" | "cn-north-1" | "cn-northwest-1" | "eu-central-1" | "eu-central-2" | "eu-north-1" | "eu-south-1" | "eu-south-2" | "eu-west-1" | "eu-west-2" | "eu-west-3" | "il-central-1" | "me-central-1" | "me-south-1" | "mx-central-1" | "sa-east-1" | "us-east-1" | "us-east-2" | "us-gov-east-1" | "us-gov-west-1" | "us-west-1" | "us-west-2" | "asia-east1" | "asia-east2" | "asia-northeast1" | "asia-northeast2" | "asia-northeast3" | "asia-south1" | "asia-south2" | "asia-southeast1" | "asia-southeast2" | "australia-southeast1" | "australia-southeast2" | "europe-central2" | "europe-north1" | "europe-southwest1" | "europe-west1" | "europe-west2" | "europe-west3" | "europe-west4" | "europe-west6" | "europe-west8" | "europe-west9" | "global" | "me-central1" | "me-central2" | "me-west1" | "northamerica-northeast1" | "northamerica-northeast2" | "southamerica-east1" | "us-central1" | "us-east1" | "us-east4" | "us-east5" | "us-south1" | "us-west1" | "us-west2" | "us-west3" | "us-west4" | "datazone_eu" | "datazone_us" | "us" | "eu";
        } & (components["schemas"]["Cost"] & unknown);
        /** @description Schema for default.yaml files (provider-level defaults) */
        DefaultConfig: {
            /** @description Official documentation links for models, pricing, and deprecations */
            documentation?: string[];
            messages?: components["schemas"]["MessageConfig"];
            /** @description Configurable parameters with defaults */
            params?: components["schemas"]["ModelParam"][];
            tool_pricing?: components["schemas"]["ToolPricing"];
        };
        /**
         * @description Provider-specific configuration that cannot be expressed through the generic
         *     fields above. Each key is owned by exactly one provider.
         */
        ExtraConfiguration: {
            /**
             * @description Path segment AWS serves this model under on the bedrock-mantle endpoint,
             *     injected before `/v1/...`. Taken from the bedrock-mantle row of the model
             *     card's Programmatic Access table, and includes the leading slash.
             *     Prefer omitting this field for models on the plain `/v1/...` path; "/" says
             *     the same thing explicitly and the gateway treats the two identically.
             * @enum {string}
             */
            bedrock_mantle_adhoc_prefix?: "/" | "/anthropic" | "/openai";
        };
        /**
         * @description Supported feature flags a model can declare
         * @enum {string}
         */
        Feature: "assistant_prefill" | "cache_control" | "code_execution" | "function_calling" | "json_output" | "parallel_function_calling" | "prompt_caching" | "structured_output" | "system_messages" | "tool_choice";
        /**
         * @description GCP region identifiers
         * @enum {string}
         */
        GCPRegion: "asia-east1" | "asia-east2" | "asia-northeast1" | "asia-northeast2" | "asia-northeast3" | "asia-south1" | "asia-south2" | "asia-southeast1" | "asia-southeast2" | "australia-southeast1" | "australia-southeast2" | "europe-central2" | "europe-north1" | "europe-southwest1" | "europe-west1" | "europe-west2" | "europe-west3" | "europe-west4" | "europe-west6" | "europe-west8" | "europe-west9" | "global" | "me-central1" | "me-central2" | "me-west1" | "northamerica-northeast1" | "northamerica-northeast2" | "southamerica-east1" | "us-central1" | "us-east1" | "us-east4" | "us-east5" | "us-south1" | "us-west1" | "us-west2" | "us-west3" | "us-west4";
        Limits: {
            context_window?: number;
            max_input_tokens?: number;
            max_output_tokens?: number;
            max_query_tokens?: number;
            max_tokens?: number;
            output_vector_size?: number;
            tool_use_system_prompt_tokens?: number;
        };
        MessageConfig: {
            options?: components["schemas"]["MessageOption"][];
        };
        /**
         * @description Message role values supported by a model or provider
         * @enum {string}
         */
        MessageOption: "assistant" | "developer" | "system" | "user";
        Modalities: {
            input?: components["schemas"]["Modality"][];
            output?: components["schemas"]["Modality"][];
        };
        /**
         * @description Input/output modality types
         * @enum {string}
         */
        Modality: "audio" | "code" | "doc" | "embedding" | "image" | "pdf" | "text" | "video";
        /**
         * @description Canonical mode values for a model
         * @enum {string}
         */
        Mode: "audio_transcription" | "audio_translation" | "chat" | "completion" | "embedding" | "image" | "moderation" | "ocr" | "realtime" | "rerank" | "responses" | "text_to_speech" | "unknown" | "unsupported" | "video";
        ModelConfig: {
            /** @description Pricing entries per region; use "*" for global/uniform pricing */
            costs?: components["schemas"]["CostWithRegion"][];
            /** @description Date after which the model is considered deprecated (YYYY-MM-DD) */
            deprecationDate?: string;
            extra_configuration?: components["schemas"]["ExtraConfiguration"];
            /** @description Feature flags for capabilities like function calling, prompt caching, etc. */
            features?: components["schemas"]["Feature"][];
            /** @description Whether the model is deprecated */
            isDeprecated?: boolean;
            limits?: components["schemas"]["Limits"];
            messages?: components["schemas"]["MessageConfig"];
            modalities?: components["schemas"]["Modalities"];
            mode: components["schemas"]["Mode"];
            /** @description Required: Model identifier used by the provider's API */
            model: string;
            /** @description Param overrides or additions relative to the provider default */
            params?: components["schemas"]["ModelParam"][];
            provisioning?: components["schemas"]["Provisioning"];
            /** @description Param keys to remove from the provider default */
            removeParams?: components["schemas"]["ModelParamKey"][];
            /** @description Param keys that must always be provided by callers */
            requiredParams?: components["schemas"]["ModelParamKey"][];
            /** @description Retirement date of the model (YYYY-MM-DD) */
            retirementDate?: string;
            /** @description Documentation or pricing source URLs */
            sources?: string[];
            status?: components["schemas"]["Status"];
            /** @description Additional modes this model can be accessed through beyond its primary mode */
            supportedModes?: components["schemas"]["Mode"][];
            /** @description Whether the model supports extended thinking / reasoning */
            thinking?: boolean;
        };
        ModelParam: {
            defaultValue?: (string | number | boolean) | null;
            key: components["schemas"]["ModelParamKey"];
            maxValue?: number;
            minValue?: number;
            supportedValues?: string[];
            type?: components["schemas"]["ModelParamType"];
        };
        /** @enum {string} */
        ModelParamKey: "json_schema" | "max_completion_tokens" | "max_tokens" | "min_tokens" | "n" | "parallel_tool_calls" | "reasoning" | "reasoning_effort" | "response_format" | "seed" | "stop" | "stream" | "temperature" | "thinking" | "tool_choice" | "top_k" | "top_p" | "verbosity";
        /** @enum {string} */
        ModelParamType: "array-of-strings" | "boolean" | "json" | "number" | "string";
        /**
         * @description How the model prices long context tokens
         *     marginal: remaining tokens after long context are priced under long context pricing
         *     cumulative: all input tokens are priced under long context pricing
         * @default marginal
         * @enum {string}
         */
        PricingMode: "marginal" | "cumulative";
        PricingTier: {
            cost_per_token: number;
            from: number;
        };
        /**
         * @description Schema for provider-config.yaml files (provider-scoped, not per-model).
         *     Every field is optional so future provider-scoped settings can slot in.
         */
        ProviderConfig: {
            /** @description anthropic-beta translation keyed by provider flavor (e.g. invoke/converse, or default) */
            anthropic_betas?: {
                [key: string]: components["schemas"]["BetaColumn"];
            };
            /** @description server-tool translation keyed by provider flavor (e.g. invoke/converse, or default) */
            server_tools?: {
                [key: string]: components["schemas"]["ServerToolColumn"];
            };
        };
        /**
         * @description How the model is made available to callers
         * @enum {string}
         */
        Provisioning: "serverless" | "provisioned";
        /** @description One server-tool column: client tool type -> provider mapping */
        ServerToolColumn: {
            [key: string]: components["schemas"]["ServerToolMapping"];
        };
        /** @description One server-tool mapping. A null type drops the tool; betas are added when it survives. */
        ServerToolMapping: {
            betas?: string[];
            type: string | null;
        };
        /**
         * @description Lifecycle status of a model
         * @enum {string}
         */
        Status: "active" | "deprecated" | "preview" | "retired";
        TieredPricing: {
            cache_read?: components["schemas"]["PricingTier"][];
            cache_write?: components["schemas"]["PricingTier"][];
            input?: components["schemas"]["PricingTier"][];
            output?: components["schemas"]["PricingTier"][];
            pricing_mode?: components["schemas"]["PricingMode"];
        };
        /** @description Pricing per billing unit; value is the cost */
        ToolCost: {
            /** @description pricing in USD */
            per_request?: number;
            per_thousand_requests?: number;
        };
        /** @description Pricing for built-in tools that can incur usage-based pricing beyond token costs */
        ToolPricing: {
            web_search?: components["schemas"]["ToolCost"];
        };
        /**
         * @description Vertex region identifiers
         * @enum {string}
         */
        VertexRegion: "us" | "eu";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type AWSRegion = components['schemas']['AWSRegion'];
export type AzureRegion = components['schemas']['AzureRegion'];
export type BetaColumn = components['schemas']['BetaColumn'];
export type Cost = components['schemas']['Cost'];
export type CostWithRegion = components['schemas']['CostWithRegion'];
export type DefaultConfig = components['schemas']['DefaultConfig'];
export type ExtraConfiguration = components['schemas']['ExtraConfiguration'];
export type Feature = components['schemas']['Feature'];
export type GCPRegion = components['schemas']['GCPRegion'];
export type Limits = components['schemas']['Limits'];
export type MessageConfig = components['schemas']['MessageConfig'];
export type MessageOption = components['schemas']['MessageOption'];
export type Modalities = components['schemas']['Modalities'];
export type Modality = components['schemas']['Modality'];
export type Mode = components['schemas']['Mode'];
export type ModelConfig = components['schemas']['ModelConfig'];
export type ModelParam = components['schemas']['ModelParam'];
export type ModelParamKey = components['schemas']['ModelParamKey'];
export type ModelParamType = components['schemas']['ModelParamType'];
export type PricingMode = components['schemas']['PricingMode'];
export type PricingTier = components['schemas']['PricingTier'];
export type ProviderConfig = components['schemas']['ProviderConfig'];
export type Provisioning = components['schemas']['Provisioning'];
export type ServerToolColumn = components['schemas']['ServerToolColumn'];
export type ServerToolMapping = components['schemas']['ServerToolMapping'];
export type Status = components['schemas']['Status'];
export type TieredPricing = components['schemas']['TieredPricing'];
export type ToolCost = components['schemas']['ToolCost'];
export type ToolPricing = components['schemas']['ToolPricing'];
export type VertexRegion = components['schemas']['VertexRegion'];
