documentation:
    - https://platform.claude.com/docs/en/home
    - https://claude.com/pricing
    - https://platform.claude.com/docs/en/about-claude/models/overview
    - https://platform.claude.com/docs/en/about-claude/model-deprecations
messages:
    options:
        - system
        - user
        - assistant
params:
    -
        defaultValue: 256
        key: max_tokens
        maxValue: 4096
        minValue: 1
    -
        defaultValue: 0.7
        key: temperature
        maxValue: 1
        minValue: 0
    -
        defaultValue: 1
        key: top_p
        maxValue: 1
        minValue: 0
    -
        defaultValue: 0
        key: top_k
        maxValue: 100
        minValue: 0
    -
        defaultValue: null
        key: stop
        skipValues:
            - null
            - []
        type: array-of-strings
    -
        defaultValue: true
        key: stream
        type: boolean
    -
        defaultValue: null
        key: tool_choice
        options:
            -
                name: None
                value: none
            -
                name: Auto
                value: auto
            -
                name: Required
                value: required
            -
                name: Custom
                schema:
                    type: json
                value: custom
        rule:
            default:
                condition: tools
                else: null
                then: auto
        skipValues:
            - null
            - []
        type: non-view-manage-data
type:
    primary: chat
    supported:
        - cache_control
