params:
  - key: max_tokens
    defaultValue: 512
    minValue: 1
    maxValue: 2048
  - key: temperature
    defaultValue: 0.5
    minValue: 0
    maxValue: 1
  - key: top_p
    defaultValue: 0.9
    minValue: 0
    maxValue: 1
  - key: 'n'
    defaultValue: 1
    minValue: 1
    maxValue: 10
  - key: stop
    defaultValue: null
    type: array-of-strings
    skipValues:
      - null
      - []
  - key: stream
    defaultValue: true
    type: boolean
messages:
  options:
    - system
    - user
    - assistant
type:
  primary: chat
  supported:
    - cache_control
